---
- hosts: all 
  tasks:
  - name: Fecha
    win_command: cmd.exe /c date /t
    register: fecha
  - debug: 
      var: fecha

  - name: Hora
    win_command: cmd.exe /c time /t
    register: hora
  - debug: 
      var: hora
      
  - name: Nombre Host
    win_command: cmd.exe /c hostname
    register: hostname
  - debug: 
      var: hostname
      
  - name: Prueba Ping
    win_command: cmd.exe /c ping cs02-cap-triara
    register: ping
  - debug: 
      var: ping
 
  - name: Direcciones IP
    win_command: cmd.exe /c ipconfig
    register: ip
  - debug: 
      var: ip
      
  - name: Rutas
    win_command: cmd.exe /c route print
    register: route
  - debug: 
      var: route
      
  - name: Servicios
    win_command: cmd.exe /c net start
    register: servicios
  - debug: 
      var: servicios

  - name: Archivo Host
    win_command: cmd.exe /c type hosts
    args:
      chdir: C:\Windows\System32\drivers\etc
    register: hosts
  - debug: 
      var: hosts
  
