---
- hosts: all 
  tasks:
  - name: Fecha y Hora
    command: date
    register: fecha
  - debug: 
      var: fecha
   
  - name: Nombre Host
    command: hostname
    register: hostname
  - debug: 
      var: hostname
      
  - name: Prueba Ping
    command: ping -c3 cs02-cap-triara
    register: ping
  - debug: 
      var: ping
 
  - name: Direcciones IP
    command: ip a
    register: ip
  - debug: 
      var: ip
      
  - name: Rutas
    command: ip route
    register: route
  - debug: 
      var: route
      
  - name: Servicios List
    command: simpana list
    register: servicios1
  - debug: 
      var: servicios1
      
  - name: Servicios Status
    command: simpana status
    register: servicios2
  - debug: 
      var: servicios2

  - name: Archivo Host
    command: cat /etc/hosts
    register: hosts
  - debug: 
      var: hosts
