---
- hosts: all 
  tasks:
  - name: Save the result of hostname 2
    win_command: cmd.exe /c hostname
    register: host1_info
 
  - name: Save the result of hostname 2
    win_shell: hostname
    args:
      executable: cmd
    register: hots2_info
