---
- hosts: all 
  tasks:
  - name: Save the result of 'whoami' in 'whoami_info'
    win_command: cmd.exe /c hostname
    register: whoami_info
 
  - win_shell: hostname
    args:
      executable: cmd
    register: ip_info
