---
- hosts: all
  tasks:
  - name: Copiar Script a Servidor
    win_copy:
      src: /var/lib/awx/projects/glamprea/Consultahtml.ps1
      dest: C:\Temp\Consultahtml.ps1

  - name: Ejecutar Script en PowerShell
    win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Temp\Consultahtml.ps1
    register: result
  
  - name: Eliminar Script en Servidor
    win_find:
      paths: C:\Temp
      patterns: 'Consultahtml.ps1'
      age: 0d
      file_type: file
    register: files_to_delete

  - name: Ansible Remove Files Older
    win_file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
  
  - name: Send e-mail
    mail:
      host: localhost
      port: 25
      subject: Resultado Consulta Servicios
      body: Hola, este es el resultado de la consulta de servicios con PowerShell
      from: ansible@telmexla.net.co
      to: gustavo.lamprea@claro.com.co
      attach: C:\temp\servicios.html
      secure: starttls
